### ISSUE TITLE
GDPR compatibility in responsive view

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#10]
Bagisto v1.2.0

data-request sidebar icon is missing at customer end for responsive view
![Screenshot_141](https://user-images.githubusercontent.com/43210406/100082143-dc768580-2e6d-11eb-97ec-87330e8f2b2d.png)

**Comment by vaishaliwebkul** [comment]
cookie block in mobile view need to be fix 
![Screenshot_165](https://user-images.githubusercontent.com/43210406/101057586-35eb5c80-35b2-11eb-8a5f-f15bd0e506a4.png)

**Comment by akhtarkhan1** [comment]
Fixed --  https://prnt.sc/vx8v5g

**Comment by akhtarkhan1** [comment]
Fixed -- https://prnt.sc/zzjoyw

**Comment by vaishaliwebkul** [comment]
fixed
