### ISSUE TITLE
company name is not coming in data request document

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#13]
Bagisto v1.2.0

![Screenshot_148](https://user-images.githubusercontent.com/43210406/100119975-773a8880-2e9d-11eb-8650-b0ae1157ac1e.png)

![Screenshot_149](https://user-images.githubusercontent.com/43210406/100120012-7e619680-2e9d-11eb-83ce-5d1f60fcf044.png)

**Comment by vaishaliwebkul** [comment]
company name is not coming in order details.
![Screenshot_172](https://user-images.githubusercontent.com/43210406/101172239-f03c9b80-3666-11eb-8edb-26c8d1a13b6e.png)

**Comment by akhtarkhan1** [comment]
Fixed https://github.com/bagisto/bagisto-gdpr/commit/b030df12dc6be4a3da13d10375b77cc57cd09dde
