### ISSUE TITLE
all the customer order should visible in html or pdf

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#15]
bagisto v1.2.0

only single order is visible to customer
only single address is visible to customer

![Screenshot_152](https://user-images.githubusercontent.com/43210406/100204166-8a933580-2f29-11eb-839f-24320abd6709.png)

![Screenshot_156](https://user-images.githubusercontent.com/43210406/100208863-325f3200-2f2f-11eb-957b-bdefb5f24caa.png)

![Screenshot_153](https://user-images.githubusercontent.com/43210406/100204197-94b53400-2f29-11eb-97d1-133afb141b75.png)

**Comment by vaishaliwebkul** [comment]
getting an exception when open the pdf https://prnt.sc/vvsjoq

**Comment by akhtarkhan1** [comment]
Fixed -- https://github.com/bagisto/bagisto-gdpr/commit/9311d38d34a3e495a2795973d06df77c19fbe9fd

**Comment by vaishaliwebkul** [comment]
fixed
