### ISSUE TITLE
getting issue to adding long text while requesting for update data

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#16]
bagisto v1.2.0

- design issue in email template when add long text 
![Screenshot_154](https://user-images.githubusercontent.com/43210406/100205951-bfa08780-2f2b-11eb-814f-efd525bbfaec.png)

- admin gets only half data as the input field is added 
![Screenshot_155](https://user-images.githubusercontent.com/43210406/100206255-1b6b1080-2f2c-11eb-921e-904785a19fee.png)

Excepted Result

- add length validation for 250 words.

- add textarea in message field instead of input field

**Comment by vaishaliwebkul** [comment]
@akhtarkhan1 
add max limit of total 500 words in this field, as currently half of the text, is removed when submitting data request

**Comment by akhtarkhan1** [comment]
Fixed -- https://prnt.sc/vx9fpg

**Comment by vaishaliwebkul** [comment]
fixed
