### ISSUE TITLE
customer should notified when admin update the request status

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#17]
bagisto v1.2.0

customer should receive an email notification when admin update request status "processing", "declined", "complete"

**Comment by akhtarkhan1** [comment]
Done - https://github.com/bagisto/bagisto-gdpr/commit/ab0f8ce4531b589eca7b19f8704d0e8f18413e7d

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/15lzazb
