### ISSUE TITLE
Agreement Checkbox Label should be mark as mandatory field

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#19]
![Screenshot_168](https://user-images.githubusercontent.com/43210406/101127099-ceb9c080-3622-11eb-880b-d7ae19fb0a45.png)

**Comment by akhtarkhan1** [comment]
Fixed -- https://prnt.sc/vx9rq6

**Comment by akhtarkhan1** [comment]
https://github.com/bagisto/bagisto-gdpr/commit/686295676d745ed20c479c420957ccf8a7cb0ea2
https://prnt.sc/zz8kr2
