### ISSUE TITLE
not getting address details in document if customer order doesn't exist

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#21]
customer order does not print in the document if customer address does not exist

![Screenshot_171](https://user-images.githubusercontent.com/43210406/101171143-6213e580-3665-11eb-8088-f6fd9d4bbc30.png)

**Comment by akhtarkhan1** [comment]
Fixed  --- https://prnt.sc/vxbct7

**Comment by vaishaliwebkul** [comment]
fixed
