### ISSUE TITLE
request update or delete field should be mark with mandatory icon

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#22]
customer -> data request-> request for update or delete should mark with mandatory icon and also show the js error instead of popup

![Screenshot_173](https://user-images.githubusercontent.com/43210406/101176208-2f212000-366c-11eb-8d72-98a35168dac0.png)

**Comment by akhtarkhan1** [comment]
Fixed -- https://prnt.sc/vxf5mq

**Comment by akhtarkhan1** [comment]
Can't use jquery validation on this page. So that's why the alert box is there instead of that.

**Comment by vaishaliwebkul** [comment]
fixed
