### ISSUE TITLE
cross icon should be clickable in content screen

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#23]
![Screenshot_174](https://user-images.githubusercontent.com/43210406/101176669-cf774480-366c-11eb-9044-d1410ac0c053.png)

**Comment by akhtarkhan1** [comment]
Fixed -  https://github.com/bagisto/bagisto-gdpr/commit/2e0ddffd4601022ebe747e14f433380a2c885c41
