### ISSUE TITLE
add /src at the end of composer.json

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#26]
"Webkul\\GDPR\\": "packages/Webkul/GDPR"

should be

"Webkul\\GDPR\\": "packages/Webkul/GDPR/src" which support in latest composer v 2.0

**Comment by akhtarkhan1** [comment]
Added - https://github.com/bagisto/bagisto-gdpr/commit/fcd624950b6bf1fe5e39744ae76350213024642b

**Comment by vaishaliwebkul** [comment]
fixed
