### ISSUE TITLE
compatibility of GDPR with Bagisto v1.3.1

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#28]
Bagisto v1.3.1

![Screenshot_319](https://user-images.githubusercontent.com/43210406/109815398-9a6f9380-7c55-11eb-8b69-30441ec7ffd2.png)

**Comment by akhtarkhan1** [comment]
Fixed - https://github.com/bagisto/bagisto-gdpr/commit/ba95f20561d451641bb5a2ca39f9a0da9d7d18a9

**Comment by vaishaliwebkul** [comment]
fixed
