### ISSUE TITLE
delete request mail consist static email id & static text

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto-gdpr#37]
Kindly remove the static user email from the below file

https://github.com/bagisto/bagisto-gdpr/blob/master/src/Mail/DataDeleteRequestMail.php#L27

**Comment by akhtarkhan1** [comment]
Fixed - https://github.com/bagisto/bagisto-gdpr/commit/5f5462fc84953809997ea21e2f913098de99bcd5

**Comment by vaishaliwebkul** [comment]
@akhtarkhan1 
Kindly update the translation also as mentioned here https://github.com/bagisto/bagisto-gdpr/commit/5f5462fc84953809997ea21e2f913098de99bcd5

**Comment by akhtarkhan1** [comment]
Added translation - https://github.com/bagisto/bagisto-gdpr/commit/afb21d1b88ac8945cb7ce993b4dd86ceca7f2fd2
