### ISSUE TITLE
Cookies Consent Manager

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto-gdpr#40]
## Feature Request
The cookie solution/consent manager is essential since every website in Europe needs it by law. As long as the user does not accept cookies, the website is not allowed to set any cookies (except technically required cookies).

Once the user agrees or sets his preferences, the website can set cookies for tracking, marketing, etc.

Thus, the solution must be able to deliver scripts that use cookies depending on the settings of the user. Without such a solution you can not create a bagisto-based webshop in Europe.

**Comment by nicolaisen** [comment]
Any update on this?

**Comment by CoE2013** [comment]
does this not work with release 1.3.3 (seems like the cookie hint is not visible in the frontend)?

**Comment by akhtarkhan1** [comment]
Feature Implemented
https://github.com/bagisto/bagisto-gdpr/pull/47/commits/8025dcb6053d6600999c72594f0672d2d6cee5e9
