### ISSUE TITLE
View [UI.particals] not found.

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto-gdpr#44]
View [UI.particals] not found. (View: /var/www/html/bagisto/resources/themes/velocity/views/layouts/master.blade.php)

**Comment by rumensys** [comment]
Can you solve that problem, please.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

Please share bagisto version and module version.

**Comment by rumensys** [comment]
Bagisto 1.3.3 fresh install
Gdpr latest download zip from master
