### ISSUE TITLE
issue #44 

### ISSUE THREAD

**Issue by anmol-webkul** [bagisto/bagisto-gdpr#48]
composer require bagisto/bagisto-gdpr
it installs the old version with the error
When I merged master from GitHub into gdpr folder and then run
php artisan gdpr:install

then all runs OK.

Please update the command composer require, so users receive the last version and will not receive any errors. Thank you a lot for your hard work! Regards. You can now close all tickets. Thank you

**Comment by ghermans** [comment]
Done
