### ISSUE TITLE
No user GDPR consent appears at the frontend

### ISSUE THREAD

**Issue by stoney024** [bagisto/bagisto-gdpr#7]
After the module install, and enabling at the admin, I can't see any GDPR notice at the frontend.
Enabled GDPR, Enabled Customer Data Agreement, Enabled Cookie Notice : all 3 enabled.

Bagisto 1.1.2.

**Comment by ghermans** [comment]
@akhtarkhan1 @jitendra-webkul i confirm that this is a bug

**Comment by ghermans** [comment]
@akhtarkhan1 do you have any update regarding this issue?

**Comment by akhtarkhan1** [comment]
@ghermans I am checking the issue, I will update you.

**Comment by vaishaliwebkul** [comment]
@stoney024 @ghermans 

This bug is resolved now, kindly update GDPR with master branch.
![Screenshot_169](https://user-images.githubusercontent.com/43210406/101127292-47208180-3623-11eb-9a81-d777a79f6c1c.png)

**Comment by ghermans** [comment]
true but the colours don't really match with the Velocity theme

**Comment by vaishaliwebkul** [comment]
@ghermans 
Yes exactly, the cookie block representation is not good enough for now, I will get this update too as soon as possible.

**Comment by vaishaliwebkul** [comment]
UI is updated for cookie notification
![Screenshot_398](https://user-images.githubusercontent.com/43210406/122217724-508c7f80-cecb-11eb-87d0-d9f07e03c9d4.png)
